# Generated by Django 2.0.2 on 2018-10-15 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxAnswer',
            fields=[
                ('checkbox_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='MultichoiceAnswer',
        ),
        migrations.RenameField(
            model_name='multichoiceanswer',
            old_name='answer_id',
            new_name='multichoice_answer_id',
        ),
    ]
