# Generated by Django 2.0.2 on 2018-11-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181015_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='prev_page',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
