# Generated by Django 2.0.2 on 2018-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_page_prev_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='next_page',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
