# Generated by Django 2.0.2 on 2018-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_page_next_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='nextqp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
