# Generated by Django 2.0.2 on 2018-11-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_score_nextqp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='checkboxanswer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='title',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
